project:
  type: website

website:
  sidebar:
    style: docked
    title: "Stat 210b"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    contents:
      - href: index.qmd
        text: Home 
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



