---
title: "Statistics 210b: Theory of Statistics"
subtitle: "UC Berkeley, Spring 2025"
listing:
  - id: buttons
    template: assets/buttons.ejs
    contents: buttons.yml
---

::: {#buttons}
:::

## Description
<ul>
<li> Instructor: Song Mei (songmei [at] berkeley.edu) </li>
<li> Lectures: Tuesday/Thursday 11:00 am - 12:30 am. Evans 334. </li>
<li> Office Hours: Tuesday 1:30 pm - 3:00 pm. Evans 387. </li>
<li> GSI: Kaihao Jing (khjing [at] berkeley.edu) </li>
<li> Office Hours: TBA. </li>
<li> Discussion sessions: Every other week. Time and location TBA. </li>
</ul>

This is an advanced graduate course on mathematical statistics, following up on the introductory course STAT 210A. Topics to be covered include tail bounds and basic aspects of concentration of measure, uniform laws of large number, metric entropy and chaining arguments, Gaussian comparison inequalities, covariance estimation and non-asymptotic random matrix theory, sparse high-dimensional models, structured forms of principal component analysis, non-parametric regression, and minimax lower bounds. 

## Announcement
<ol>
<li> First class: Jan 21, 2025 (Tuesday). </li>
<li> I will process the CE students during the week of Jan 20. It may take 1-2 weeks to get you enrolled. </li>
<li> We will use Ed (https://edstem.org/us/courses/73735/discussion) for discussions and questions. Use this link (https://edstem.org/us/join/PyDUgd) to join. </li>
<li> Please submit HW using Gradescope (https://www.gradescope.com/courses/953916, code: WW73Y5). </li>
<li> Please find homework and lecture notes on bCourse (https://bcourses.berkeley.edu/courses/1542128/) under “Files”. </li>
<li> (It is not sure yet if there is Course Capture system in Evans 334) The lectures will be recorded through Course Capture. The recordings can be found on bCourse under “Media Gallery”. </li>
</ol>


## Grading
<ul>
<li> Class attendance is required.</li>
<li> Homework per two weeks. There will be 5-6 HWs.</li>
<li> In class mid-term: TBA. </li>
<li> Final exam date: Thursday, May 15, 2025. 8–11 am. </li>
<li> Final grade will be Homework x 35 \% \+ mid-term x 25 \% \+ final x 40 \%.</li>
<li> HW policy: There are in total three late days that you can use without penalty towards grade throughout the semester. After that, there will be a 10% deduction on grades of a HW for each late day. The least grade can be dropped counting towards total grades.</li>
</ul> 

## Prerequisites

All students should have taken STAT 210A or an equivalent course in basic mathematical statistics, and must have a strong background in probability and real analysis. This course requires some degree of mathematical maturity. 


## Topics 

Concentration inequalities, empirical process theory, random matrix theory, sparse high-dimensional models, non-parametric regression, and minimax lower bounds. 

<!---
For a style similar to that of [Stat 20](https://stat20.org), modify `index.qmd` to point to `assets/{schedule-alt.ejs,buttons-alt.ejs}` and to `{schedule-alt.yml,buttons-alt.yml}` and `_quarto.yml` to point to `assets/styles-alt.scss`.
-->

## Syllabus

Syllabus can be found here (https://github.com/berkeley-stat210b/spring-2025/blob/main/Syllabus_STAT210B_Spring2025.pdf). 